language: ruby

rvm:
  - 2.2.2

gemfile:
  - Gemfile

services:
  - mongodb

env:
  - CODECLIMATE_REPO_TOKEN=b216164ab66da464aa02fe5b862811ba0526c8dc7ea291ebe53056be4b6b5e1f

script: "bundle exec rspec"
